- version: 1.0.0
  date: 07-18-2023
  alert:
    fatal:
      enabled: true
      type: 
        - log
        #- email
      to:
        - myEmail@gmail.com
    error:
      enabled: true
      type: 
        - log
        #- email
        #- sms
      to: 
        - myEmail@gmail.com
    warning:
      enabled: true
      type: 
        - log
        #- email
      to:
        - myEmail@gmail.com
    info:
      enabled: true
      type: 
        - log
        #- email
      to: 
        - myEmail@gmail.com
    global:
      enabled: true
      type: 
        - log
        #- webhook
        #- sms
        #- email
      to: 
        #- http://127.0.0.1:5000/test
        - myEmail@gmail.com
      conditions:
        - level: 0
          min: 1
        - level: 1
          min: 1
        - level: 2
          min: 1
        - level: 3
          min: 1
  rules:
   # storage rule
    - name: "aws-bucket-public-access-block"
      description: "this rule is to verify if the public access block is enabled on the bucket"
      applied: true
      level: 1
      cloudProvider: aws
      objectName: S3Client.PublicAccessBlock
      conditions:
        - operator: AND
          criteria:
            - property: PublicAccessBlockConfiguration.BlockPublicAcls
              condition: EQUAL
              value: true
            - property: PublicAccessBlockConfiguration.IgnorePublicAcls
              condition: EQUAL
              value: true
            - property: PublicAccessBlockConfiguration.BlockPublicPolicy
              condition: EQUAL
              value: true
            - property: PublicAccessBlockConfiguration.RestrictPublicBuckets
              condition: EQUAL
              value: true
    - name: "azure-storage-account-no-public-access"
      description: "this rule is to check on azure storage account for public access"
      applied: true
      level: 1
      cloudProvider: azure
      objectName: StorageManagementClient.storageAccounts
      conditions:
        - property: publicNetworkAccess
          condition: DIFFERENT
          value: 'Enabled'
    - name: "azure-storage-account-encryption-enabled"
      description: "this rule is to check on azure storage account for encryption enabled"
      applied: true
      level: 1
      cloudProvider: azure
      objectName: StorageManagementClient.storageAccounts
      conditions:
        - operator: AND
          criteria:
            - property: encryption.services.file.enabled
              condition: EQUAL
              value: true
            - property: encryption.services.blob.enabled
              condition: EQUAL
              value: true